// components/ContactForm.vue
<template>
  <div>
    <button @click="openModal" class="inline-block">
      <slot />
    </button>
    
    <div v-if="isOpen" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50" @click="closeModal">
      <div class="bg-white rounded-lg p-8 max-w-md w-full mx-4" @click.stop>
        <h3 class="text-2xl font-bold text-gray-900 mb-6">Contactez-nous</h3>
        <form @submit.prevent="submitForm" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Nom</label>
            <input v-model="form.name" type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary">
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
            <input v-model="form.email" type="email" required class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary">
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Entreprise</label>
            <input v-model="form.company" type="text" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary">
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Message</label>
            <textarea v-model="form.message" rows="4" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"></textarea>
          </div>
          <div class="flex gap-3">
            <button type="submit" class="flex-1 bg-primary hover:bg-primary/90 text-black px-4 py-2 rounded-md font-medium">
              Envoyer
            </button>
            <button type="button" @click="closeModal" class="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50">
              Annuler
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const isOpen = ref(false)
const form = ref({
  name: '',
  email: '',
  company: '',
  message: ''
})

const openModal = () => {
  isOpen.value = true
}

const closeModal = () => {
  isOpen.value = false
}

const submitForm = () => {
  // Generate email content
  const subject = `Contact Wallection - ${form.value.name}`
  const body = `
Nom: ${form.value.name}
Email: ${form.value.email}
Entreprise: ${form.value.company}

Message:
${form.value.message}
  `
  
  // Create mailto link
  const mailtoLink = `mailto:paul.bugeon@jobpass.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  
  // Open email client
  window.location.href = mailtoLink
  
  // Close modal
  closeModal()
  
  // Reset form
  form.value = {
    name: '',
    email: '',
    company: '',
    message: ''
  }
}
</script>

// components/contact-form.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Mail, Send } from "lucide-react"

interface ContactFormProps {
  children: React.ReactNode
}

export function ContactForm({ children }: ContactFormProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    organization: "",
    message: "",
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    // Create mailto link with form data
    const subject = encodeURIComponent("Demande d'information - Wallection")
    const body = encodeURIComponent(
      `Bonjour,

Je souhaite obtenir plus d'informations sur Wallection.

Nom: ${formData.name}
Email: ${formData.email}
Organisation: ${formData.organization}

Message:
${formData.message}

Cordialement,
${formData.name}`,
    )

    window.location.href = `mailto:paul.bugeon@jobpass.com?subject=${subject}&body=${body}`
    setIsOpen(false)
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData((prev) => ({
      ...prev,
      [e.target.name]: e.target.value,
    }))
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Mail className="h-5 w-5 text-primary" />
            Contactez-nous
          </DialogTitle>
          <DialogDescription>
            Remplissez ce formulaire pour nous contacter. Nous vous répondrons rapidement.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Nom complet *</Label>
            <Input
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
              placeholder="Votre nom"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email *</Label>
            <Input
              id="email"
              name="email"
              type="email"
              value={formData.email}
              onChange={handleChange}
              required
              placeholder="votre.email@exemple.com"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="organization">Organisation</Label>
            <Input
              id="organization"
              name="organization"
              value={formData.organization}
              onChange={handleChange}
              placeholder="Nom de votre organisme de formation"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            <Textarea
              id="message"
              name="message"
              value={formData.message}
              onChange={handleChange}
              placeholder="Décrivez vos besoins ou posez vos questions..."
              rows={4}
            />
          </div>
          <Button type="submit" className="w-full">
            <Send className="mr-2 h-4 w-4" />
            Envoyer le message
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  )
}
